# Generated by Django 6.0.4 on 2026-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
