# Generated by Django 6.0.4 on 2026-05-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_allproperties_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony_pics', models.ImageField(blank=True, null=True, upload_to='media/balcony/')),
                ('baproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baallpropertics', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_pics', models.ImageField(blank=True, null=True, upload_to='media/bathroom/')),
                ('brproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brallpropertics', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_pics', models.ImageField(blank=True, null=True, upload_to='media/kitchen/')),
                ('kproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kallpropertics', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='LivingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_pics', models.ImageField(blank=True, null=True, upload_to='media/livingarea/')),
                ('lproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lallpropertics', to='properties.allproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_pics', models.ImageField(blank=True, null=True, upload_to='media/rooms/')),
                ('rproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rallpropertics', to='properties.allproperties')),
            ],
        ),
    ]
